/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "ticker_prot.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

submit_result *
ticker_submit_1(submit_args *argp, CLIENT *clnt)
{
	static submit_result clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, TICKER_SUBMIT,
		(xdrproc_t) xdr_submit_args, (caddr_t) argp,
		(xdrproc_t) xdr_submit_result, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

submit_result *
ticker_xaction_1(xaction_args *argp, CLIENT *clnt)
{
	static submit_result clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, TICKER_XACTION,
		(xdrproc_t) xdr_xaction_args, (caddr_t) argp,
		(xdrproc_t) xdr_submit_result, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
