/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _TICKER_PROT_H_RPCGEN
#define _TICKER_PROT_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


typedef char *msg_t;

struct submit_args {
	msg_t msg;
};
typedef struct submit_args submit_args;

struct submit_result {
	bool_t ok;
};
typedef struct submit_result submit_result;

struct xaction_args {
	int my_id;
	msg_t msg;
	int ts;
};
typedef struct xaction_args xaction_args;

#define TICKER_PROG 400001
#define TICKER_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define TICKER_SUBMIT 1
extern  submit_result * ticker_submit_1(submit_args *, CLIENT *);
extern  submit_result * ticker_submit_1_svc(submit_args *, struct svc_req *);
#define TICKER_XACTION 2
extern  submit_result * ticker_xaction_1(xaction_args *, CLIENT *);
extern  submit_result * ticker_xaction_1_svc(xaction_args *, struct svc_req *);
extern int ticker_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define TICKER_SUBMIT 1
extern  submit_result * ticker_submit_1();
extern  submit_result * ticker_submit_1_svc();
#define TICKER_XACTION 2
extern  submit_result * ticker_xaction_1();
extern  submit_result * ticker_xaction_1_svc();
extern int ticker_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_msg_t (XDR *, msg_t*);
extern  bool_t xdr_submit_args (XDR *, submit_args*);
extern  bool_t xdr_submit_result (XDR *, submit_result*);
extern  bool_t xdr_xaction_args (XDR *, xaction_args*);

#else /* K&R C */
extern bool_t xdr_msg_t ();
extern bool_t xdr_submit_args ();
extern bool_t xdr_submit_result ();
extern bool_t xdr_xaction_args ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_TICKER_PROT_H_RPCGEN */
